[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing-baseline"
a = "double-storey-serifed"
f = "flat-hook-serifless-crossbar-at-x-height"
j = "flat-hook-serifed"
r = "compact-serifed"
t = "flat-hook-short-neck"
y = "straight-turn-serifless"
one = "base"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
seven = "straight-serifed"
eight = "two-circles"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-custom.variants.italic]
capital-v = "curly-serifless"
b = "toothless-corner-serifless"
f = "flat-hook-tailed-crossbar-at-x-height"
r = "hookless-top-serifed"
t = "bent-hook-short-neck"
u = "toothed-serifless"
v = "curly-serifless"
y = "cursive-flat-hook-serifless"

[buildPlans.iosevka-custom.weights.regular]
shape = 450
menu = 400
css = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9
shape = "italic"
menu = "italic"
css = "italic"
