[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing-baseline"
f = "flat-hook-serifless-crossbar-at-x-height"
j = "flat-hook-serifed"
t = "flat-hook-short-neck2"
y = "straight-turn-serifless"
zero = "oval-slashed"
one = "base"
two = "straight-neck"
four = "closed"
five = "oblique-arched"
seven = "straight-serifed"
eight = "two-circles"
brace = "straight"
guillemet = "straight"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-custom.variants.italic]
capital-j = "serifed"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook-tailed-crossbar-at-x-height"
j = "serifed"
t = "bent-hook-short-neck2"
y = "cursive-serifless"

[buildPlans.iosevka-custom.weights.regular]
shape = 450
menu = 400
css = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 618
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9
shape = "italic"
menu = "italic"
css = "italic"
