[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-a = "curly-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-m = "slanted-sides-hanging-serifless"
capital-q = "crossing-baseline"
capital-r = "curly-serifless"
capital-v = "curly-serifless"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
j = "flat-hook-serifed"
r = "compact-serifed"
t = "flat-hook-short-neck"
v = "curly-serifless"
w = "curly-serifless"
y = "straight-turn-serifless"
two = "straight-neck"
four = "closed"
five = "oblique-upper-left-bar"
seven = "straight-serifed"
eight = "two-circles"
underscore = "above-baseline"
paren = "large-contour"
number-sign = "slanted"
ampersand = "upper-open"
dollar = "through-cap"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-custom.variants.italic]
capital-u = "tailed-serifless"
capital-v = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifless"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-earless-corner"
h = "tailed-serifless"
j = "serifed"
m = "tailed-serifless"
n = "tailed-serifless"
q = "earless-corner-tailed-serifless"
r = "hookless-top-serifed"
t = "standard-short-neck"
v = "curly-serifless"
y = "cursive-serifless"

  [buildPlans.iosevka-custom.ligations]
  inherits = "clike"
  enables = [
    "connected-underline",
    "connected-number-sign",
    "connected-tilde-as-wave",
    "connected-hyphen-as-semi-dashed-line",
  ]

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
