[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing"
capital-w = "straight-flat-top"
f = "flat-hook-crossbar-at-x-height"
j = "flat-hook-serifed"
r = "compact-serifed"
t = "flat-hook-short-neck"
w = "straight-flat-top"
y = "straight-turn"
one = "base"
two = "straight-neck"
five = "oblique-upper-left-bar"
seven = "straight-serifed"
eight = "two-circles"
paren = "large-contour"
number-sign = "slanted"
ampersand = "upper-open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-custom.variants.italic]
capital-u = "tailed"
capital-v = "curly"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "earless-corner"
h = "tailed"
j = "serifed"
m = "tailed"
n = "tailed"
q = "earless-corner-tailed"
r = "hookless"
t = "standard-short-neck"
v = "curly"
y = "cursive"

  [buildPlans.iosevka-custom.ligations]
  inherits = "clike"
  enables = [
    "connected-underline",
    "connected-number-sign",
    "connected-tilde-as-wave",
    "connected-hyphen-as-semi-dashed-line",
  ]

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
