name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Build
        run: |
          nix build .#iosevka-custom-nerdfont
          ls -la result*

      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: ./result
