name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Build
        run: nix build .#iosevka-custom-nerdfont

      - name: Convert to zip
        run: zip font.zip -r "./result/share/fonts/ttf/IosevkaCustom Nerd Font"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "font.zip"
